
import re

EXPRESIONES = {
    1: r't[ií]tulo de grado',
    2: r't[ií]tulo de especializaci[oó]n',
    3: r'(mag[íi]ster|maestr[ií]a)',
    4: r'(doctorado|t[ií]tulo de doctor)',
    5: r'profesor titular',
    6: r'profesor asociado',
    7: r'profesor adjunto',
    8: r'jefe de trabajos pr[aá]cticos',
    9: r'ayudante de c[aá]tedra',
    10: r'curso.*posgrado|diplomatura',
    11: r'representante.*investigaci[oó]n',
    12: r'coordinador.*investigaci[oó]n',
    13: r'investigador superior.*conicet',
    14: r'investigador principal.*conicet',
    15: r'investigador independiente.*conicet',
    16: r'investigador adjunto.*conicet',
    17: r'investigador asistente.*conicet',
    18: r'director.*(i[+y]?d|investigaci[oó]n)',
    19: r'co-director.*(i[+y]?d|investigaci[oó]n)',
    20: r'miembro.*(i[+y]?d|investigaci[oó]n)',
    21: r'rector',
    22: r'vicerector',
    23: r'presidente del directorio',
    24: r'vicepresidente',
    25: r'decano',
    26: r'vicedecano',
    27: r'secretario general acad[eé]mico|secretario acad[eé]mico',
    28: r'secretario de extensi[oó]n',
    29: r'secretario de investigaci[oó]n',
    30: r'secretario general del consejo directivo',
    31: r'director institucional',
    32: r'co-director institucional',
    33: r'miembro de programa institucional',
    34: r'miembro de comisi[oó]n',
    35: r'consejero',
    36: r'delegado',
    37: r'jefe de [aá]rea',
    38: r'jefe de departamento',
    39: r'responsable de grupo de trabajo',
    40: r'dirigi[oó] tesis de doctorado',
    41: r'(dirigi[oó]|co.?dirigi[oó]) trabajo final de maestr[ií]a',
    42: r'trabajo final de especializaci[oó]n',
    43: r'tesina|trabajo final de grado',
    44: r'dirigi[oó] proyecto de i[+y]?d',
    45: r'co.?dirigi[oó] proyecto de i[+y]?d',
    46: r'director.*proyecto de i[+y]?d',
    47: r'co.?director.*proyecto de i[+y]?d',
    48: r'particip[oó] en categorizaci[oó]n de docentes investigadores',
    49: r'evalu[oó] investigadores',
    50: r'evalu[oó] becarios',
    51: r'jurado.*concursos docentes',
    52: r'evalu[oó] programas|proyectos de i[+y]?d|extensi[oó]n',
    53: r'jurado.*tesis doctoral',
    54: r'jurado.*tesis de maestr[ií]a',
    55: r'jurado.*tesis de especializaci[oó]n',
    56: r'evalu[oó] proyectos',
    57: r'evalu[oó] programas',
    58: r'evalu[oó] revistas científicas|revistas de cy[t]',
    59: r'curriculares.*instituciones universitarias',
    60: r'evalu[oó] planes|pol[ií]ticas',
    61: r'evalu[oó] carreras de grado|postgrado',
    62: r'evaluaci[oó]n institucional externa',
    63: r'premio',
    64: r'public[oó] libro',
    65: r'public[oó] cap[ií]tulo|parte de libro',
    66: r'trabajo.*evento cient[ií]fico|congreso',
    67: r'escribi[oó] tesis',
    68: r'tradujo.*art[ií]culo.*revista',
    69: r'tradujo.*(libro|parte de libro)',
    70: r'rese[nñ]a bibliogr[aá]fica',
    71: r'material did[aá]ctico sistematizado',
    72: r'innovaci[oó]n pedag[oó]gica',
    73: r'desarroll[oó] producto',
    74: r'desarroll[oó] proceso productivo',
    75: r'gesti[oó]n de la producci[oó]n',
    76: r'organizaci[oó]n de la producci[oó]n',
    77: r'coordinador acad[eé]mico.*diplomatura',
    78: r'docente.*diplomatura',
    79: r'miembro.*comit[eé] cient[ií]fico.*(jornadas|congreso)',
    80: r'actividades de extensi[oó]n|charlas abiertas',
    81: r'redes acad[eé]micas|interinstitucionales',
}

PUNTAJES = {i: 10 for i in range(1, 82)}
PUNTAJES.update({  # sobrescribimos con valores reales conocidos
    1: 30, 2: 75, 3: 150, 4: 250, 5: 100, 6: 90, 7: 80, 8: 70, 9: 60, 10: 10,
    40: 50, 41: 50, 42: 50, 43: 50, 63: 20, 64: 90, 65: 80, 66: 70,
    77: 40, 78: 30, 79: 20, 80: 15, 81: 25
})

def detectar_items(texto):
    respuestas = [0] * 82
    for item, patron in EXPRESIONES.items():
        if re.search(patron, texto, re.IGNORECASE):
            respuestas[item] = PUNTAJES[item]
    return respuestas
